// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRoleM = "sys_user_roles"

// UserRoleM mapped from table <sys_user_roles>
type UserRoleM struct {
	RoleID int64 `gorm:"column:role_id;primaryKey" json:"roleId"`
	UserID int64 `gorm:"column:user_id;primaryKey" json:"userId"`
}

// TableName UserRoleM's table name
func (*UserRoleM) TableName() string {
	return TableNameUserRoleM
}
