// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApiM = "sys_api"

// ApiM mapped from table <sys_api>
type ApiM struct {
	ID        int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *int64  `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt *int64  `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt *int64  `gorm:"column:deleted_at;comment:是否删除" json:"deletedAt"`                           // 是否删除
	MenuID    *int64  `gorm:"column:menu_id;comment:菜单id" json:"menuId"`                                 // 菜单id
	Name      string  `gorm:"column:name;not null;comment:权限名称" json:"name"`                             // 权限名称
	Desc      *string `gorm:"column:desc;comment:权限描述" json:"desc"`                                      // 权限描述
	Method    string  `gorm:"column:method;not null;comment:HTTP方法(GET,POST,PUT,DELETE)" json:"method"`  // HTTP方法(GET,POST,PUT,DELETE)
	Path      string  `gorm:"column:path;not null;comment:路由路径(比如/api/users)" json:"path"`               // 路由路径(比如/api/users)
	Auth      *string `gorm:"column:auth;default:2;comment:是否需要权限1需要2不需要" json:"auth"`                   // 是否需要权限1需要2不需要
}

// TableName ApiM's table name
func (*ApiM) TableName() string {
	return TableNameApiM
}
