// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleApisM = "sys_role_apis"

// RoleApisM mapped from table <sys_role_apis>
type RoleApisM struct {
	RoleID int64 `gorm:"column:role_id;primaryKey" json:"roleId"`
	APIID  int64 `gorm:"column:api_id;primaryKey" json:"apiId"`
}

// TableName RoleApisM's table name
func (*RoleApisM) TableName() string {
	return TableNameRoleApisM
}
