// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsersM = "sys_users"

// UsersM mapped from table <sys_users>
type UsersM struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     *int64  `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt     *int64  `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt     *int64  `gorm:"column:deleted_at;comment:是否删除" json:"deletedAt"`                           // 是否删除
	CreateByID    *int64  `gorm:"column:create_by_id;comment:创建人id" json:"createById"`                       // 创建人id
	UpdateByID    *int64  `gorm:"column:update_by_id;comment:更新人id" json:"updateById"`                       // 更新人id
	UserName      string  `gorm:"column:user_name;not null" json:"userName"`
	Password      string  `gorm:"column:password;not null" json:"password"`
	Status        *string `gorm:"column:status;default:1;comment:是否启用0禁用1启用" json:"status"`      // 是否启用0禁用1启用
	UserGender    *string `gorm:"column:user_gender;default:1;comment:性别1男2女" json:"userGender"` // 性别1男2女
	NickName      *string `gorm:"column:nick_name;comment:昵称" json:"nickName"`                   // 昵称
	UserPhone     *string `gorm:"column:user_phone;comment:手机号" json:"userPhone"`                // 手机号
	UserEmail     *string `gorm:"column:user_email;comment:邮箱" json:"userEmail"`                 // 邮箱
	LastLoginTime *int64  `gorm:"column:last_login_time" json:"lastLoginTime"`
}

// TableName UsersM's table name
func (*UsersM) TableName() string {
	return TableNameUsersM
}
