// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenuM = "sys_menu"

// MenuM mapped from table <sys_menu>
type MenuM struct {
	ID              int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       *int64  `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"createdAt"`    // 创建时间
	UpdatedAt       *int64  `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updatedAt"`    // 更新时间
	DeletedAt       *int64  `gorm:"column:deleted_at;comment:是否删除" json:"deletedAt"`                              // 是否删除
	CreateByUserID  *int64  `gorm:"column:create_by_user_id;comment:创建人id" json:"createByUserId"`                 // 创建人id
	UpdateByUserID  *int64  `gorm:"column:update_by_user_id;comment:更新人id" json:"updateByUserId"`                 // 更新人id
	ParentID        int64   `gorm:"column:parent_id;not null;comment:父菜单ID,如果为0则为一级菜单" json:"parentId"`           // 父菜单ID,如果为0则为一级菜单
	MenuType        string  `gorm:"column:menu_type;not null;comment:菜单类型1目录2菜单" json:"menuType"`                 // 菜单类型1目录2菜单
	MenuName        string  `gorm:"column:menu_name;not null;comment:菜单名称" json:"menuName"`                       // 菜单名称
	RouteName       string  `gorm:"column:route_name;not null;comment:路由名称" json:"routeName"`                     // 路由名称
	RoutePath       string  `gorm:"column:route_path;not null;comment:路由路径" json:"routePath"`                     // 路由路径
	Component       string  `gorm:"column:component;not null;comment:组件名称" json:"component"`                      // 组件名称
	I18NKey         string  `gorm:"column:i18_n_key;not null;comment:国际化key" json:"i18NKey"`                      // 国际化key
	IconType        string  `gorm:"column:icon_type;not null;comment:图标类型1iconify图标你2本地图标" json:"iconType"`       // 图标类型1iconify图标你2本地图标
	Icon            string  `gorm:"column:icon;not null;comment:图标" json:"icon"`                                  // 图标
	Status          string  `gorm:"column:status;not null;default:1;comment:菜单状态1启用2禁用" json:"status"`            // 菜单状态1启用2禁用
	KeepAlive       bool    `gorm:"column:keep_alive;not null;comment:是否缓存路由" json:"keepAlive"`                   // 是否缓存路由
	Constant        bool    `gorm:"column:constant;not null;comment:是否常量路由" json:"constant"`                      // 是否常量路由
	OrderBy         int64   `gorm:"column:order_by;not null;comment:排序,在同级路由中，越小越靠前" json:"orderBy"`              // 排序,在同级路由中，越小越靠前
	Href            string  `gorm:"column:href;not null;comment:外链地址" json:"href"`                                // 外链地址
	FixedIndexInTab int64   `gorm:"column:fixed_index_in_tab;not null;comment:固定在标签页中的序号" json:"fixedIndexInTab"` // 固定在标签页中的序号
	HideInMenu      bool    `gorm:"column:hide_in_menu;not null;comment:是否隐藏菜单" json:"hideInMenu"`                // 是否隐藏菜单
	ActiveMenu      string  `gorm:"column:active_menu;not null;comment:高亮的菜单" json:"activeMenu"`                  // 高亮的菜单
	MultiTab        bool    `gorm:"column:multi_tab;not null;comment:是否支持多页签" json:"multiTab"`                    // 是否支持多页签
	Query           *string `gorm:"column:query;comment:路由参数" json:"query"`                                       // 路由参数
}

// TableName MenuM's table name
func (*MenuM) TableName() string {
	return TableNameMenuM
}
