// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleM = "sys_role"

// RoleM mapped from table <sys_role>
type RoleM struct {
	ID             int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      *int64  `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt      *int64  `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt      *int64  `gorm:"column:deleted_at;comment:是否删除" json:"deletedAt"`                           // 是否删除
	CreateByUserID *int64  `gorm:"column:create_by_user_id;comment:创建人id" json:"createByUserId"`              // 创建人id
	UpdateByUserID *int64  `gorm:"column:update_by_user_id;comment:更新人id" json:"updateByUserId"`              // 更新人id
	Name           string  `gorm:"column:name;not null;comment:角色名称" json:"name"`                             // 角色名称
	Code           string  `gorm:"column:code;not null;comment:角色编码" json:"code"`                             // 角色编码
	Desc           *string `gorm:"column:desc;comment:角色描述" json:"desc"`                                      // 角色描述
	Status         *string `gorm:"column:status;default:1;comment:是否启用0禁用1启用" json:"status"`                  // 是否启用0禁用1启用
	HomeMenuID     *int64  `gorm:"column:home_menu_id;default:1;comment:首页菜单id" json:"homeMenuId"`            // 首页菜单id
}

// TableName RoleM's table name
func (*RoleM) TableName() string {
	return TableNameRoleM
}
