// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameButtonM = "sys_button"

// ButtonM mapped from table <sys_button>
type ButtonM struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *int64 `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt *int64 `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt *int64 `gorm:"column:deleted_at;comment:是否删除" json:"deletedAt"`                           // 是否删除
	MenuID    *int64 `gorm:"column:menu_id;comment:菜单id" json:"menuId"`                                 // 菜单id
	Label     string `gorm:"column:label;not null;comment:按钮名" json:"label"`                            // 按钮名
	Code      string `gorm:"column:code;not null;comment:按钮代码" json:"code"`                             // 按钮代码
}

// TableName ButtonM's table name
func (*ButtonM) TableName() string {
	return TableNameButtonM
}
