// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleButtonM = "sys_role_buttons"

// RoleButtonM mapped from table <sys_role_buttons>
type RoleButtonM struct {
	RoleID   int64 `gorm:"column:role_id;primaryKey" json:"roleId"`
	ButtonID int64 `gorm:"column:button_id;primaryKey" json:"buttonId"`
}

// TableName RoleButtonM's table name
func (*RoleButtonM) TableName() string {
	return TableNameRoleButtonM
}
